grist:
  schemas:
    tables:
      services:
        id: Beta_Services_Numeriques
        columns:
          - id: identifiant
            fields:
              label: Identifiant
          - id: name
            fields:
              label: Nom
          - id: mission
            fields:
              label: Mission
          - id: link
            fields:
              label: Lien
          - id: impact_url
            fields:
              label: Matrice d'impact
          - id: current_phase
            fields:
              label: Phase
          - id: contact_email
            fields:
              label: Email de contact
          - id: incubator
            fields:
              label: Incubateur
          - id: incubator_contact
            fields:
              label: Contact de l'incubateur
      members:
        id: Beta_Membres
        columns:
          - id: identifiant
            fields:
              label: Identifiant
          - id: name
            fields:
              label: Nom
          - id: gender
            fields:
              label: Genre
          - id: email
            fields:
              label: Email
          - id: secondary_email
            fields:
              label: Email secondaire
          - id: domain
            fields:
              label: Domaine
          - id: active_mission
            fields:
              type: Bool
              label: Actif
          - id: end_mission
            fields:
              type: Date
              label: Date de fin de mission
